// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

// NewTodo represents new todo input
type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

// Todo represents todo type
type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

// User represents user type
type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
